// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfvomwVeIjR3c7OQyRpoD_wzMlmj92MQY',
    appId: '1:77536600159:web:9fc3e0ad24b503e8843bea',
    messagingSenderId: '77536600159',
    projectId: 'apii-444403',
    authDomain: 'apii-444403.firebaseapp.com',
    storageBucket: 'apii-444403.firebasestorage.app',
    measurementId: 'G-5N10QDNTSE',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmgSNmDCnepy9H3s70BqLMVwmpTcJwqJA',
    appId: '1:77536600159:ios:8e6b4a9dded3ebad843bea',
    messagingSenderId: '77536600159',
    projectId: 'apii-444403',
    storageBucket: 'apii-444403.firebasestorage.app',
    androidClientId: '77536600159-gnt56fukaakjq7dbcca5jjqfg83qhp8g.apps.googleusercontent.com',
    iosClientId: '77536600159-bg47p1mj04nb4g77ea9c38a6tqa958ld.apps.googleusercontent.com',
    iosBundleId: 'com.example.apii',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmgSNmDCnepy9H3s70BqLMVwmpTcJwqJA',
    appId: '1:77536600159:ios:8e6b4a9dded3ebad843bea',
    messagingSenderId: '77536600159',
    projectId: 'apii-444403',
    storageBucket: 'apii-444403.firebasestorage.app',
    androidClientId: '77536600159-gnt56fukaakjq7dbcca5jjqfg83qhp8g.apps.googleusercontent.com',
    iosClientId: '77536600159-bg47p1mj04nb4g77ea9c38a6tqa958ld.apps.googleusercontent.com',
    iosBundleId: 'com.example.apii',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfvomwVeIjR3c7OQyRpoD_wzMlmj92MQY',
    appId: '1:77536600159:web:145d777cb043ceb3843bea',
    messagingSenderId: '77536600159',
    projectId: 'apii-444403',
    authDomain: 'apii-444403.firebaseapp.com',
    storageBucket: 'apii-444403.firebasestorage.app',
    measurementId: 'G-TRETB0RQ51',
  );
}
